version: '3.8'

services:
  app:
    build: .
    image: google-trends:${VERSION:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
      - MONGO_URL=mongodb://mongo:27017/
      - MONGO_DB=google-trends
      - TELEGRAM_TOKEN=your_telegram_token
      - TELEGRAM_CHAT_ID=your_telegram_chat_id
    volumes:
      - ./data/trends-daily:/app/data/trends-daily
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db