version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/
      - MONGO_DB=local
      - TELEGRAM_TOKEN=
      - TELEGRAM_CHAT_ID=
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db